basePath: /api/BytesBytes
consumes:
    - ""
    - image/jpeg
externalDocs: {}
id: BytesBytes
info:
    description: 'BytesBytes this is bytes binding and bytes render demo this is a interface '
    title: BytesBytes
paths:
    /Get:
        get:
            consumes:
                - ""
            description: 'GetBytesBytes get http method, receive bytes request and send bytes response '
            externalDocs: {}
            operationId: /demo.BytesBytes/GetBytesBytes
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - ttt.sss
            responses: {}
            security: []
            summary: GetBytesBytes
    /Post:
        post:
            consumes:
                - image/jpeg
            description: 'PostBytesBytes post http method,  receive bytes request and send bytes response '
            externalDocs: {}
            operationId: /demo.BytesBytes/PostBytesBytes
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - text/go
            responses: {}
            security: []
            summary: PostBytesBytes
produces:
    - ttt.sss
    - text/go
schemes:
    - http
    - https
swagger: "2.0"
