basePath: /api/BytesString
consumes:
    - application/html
    - ""
externalDocs: {}
id: BytesString
info:
    description: 'BytesString '
    title: BytesString
paths:
    /Get:
        get:
            consumes:
                - application/html
            description: 'GetBytesString '
            externalDocs: {}
            operationId: /demo.BytesString/GetBytesString
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - text/html
            responses: {}
            security: []
            summary: GetBytesString
    /Put:
        put:
            consumes:
                - ""
            description: 'PutBytesString '
            externalDocs: {}
            operationId: /demo.BytesString/PutBytesString
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - ""
            responses: {}
            security: []
            summary: PutBytesString
produces:
    - text/html
    - ""
schemes:
    - http
    - https
swagger: "2.0"
