consumes:
    - ""
    - ""
    - ""
    - ""
externalDocs: {}
id: NotDefine
info:
    title: NotDefine
paths:
    /demo.notdefine/bytes:
        get:
            consumes:
                - ""
            externalDocs: {}
            operationId: /demo.NotDefine/Bytes
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - ""
            responses: {}
            security: []
            summary: Bytes
    /demo.notdefine/notdefine:
        get:
            consumes:
                - ""
            externalDocs: {}
            operationId: /demo.NotDefine/NotDefine
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
            produces:
                - application/json
            responses: {}
            security: []
            summary: NotDefine
    /demo.notdefine/reader:
        get:
            consumes:
                - ""
            externalDocs: {}
            operationId: /demo.NotDefine/Reader
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - ""
            responses: {}
            security: []
            summary: Reader
    /demo.notdefine/string:
        get:
            consumes:
                - ""
            externalDocs: {}
            operationId: /demo.NotDefine/String
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - ""
            responses: {}
            security: []
            summary: String
produces:
    - ""
    - ""
    - ""
    - application/json
schemes:
    - http
    - https
swagger: "2.0"
