basePath: /api/ObjObj
consumes:
    - application/json
    - ""
    - ""
    - ""
    - application/json
    - application/xml
    - application/x-www-form-urlencoded
    - application/x-www-form-urlencoded
    - multipart/form-data
    - application/x-protobuf
    - application/x-msgpack
    - application/x-yaml
    - application/toml
    - application/json
externalDocs: {}
id: ObjObj
info:
    description: 'ObjObj '
    title: ObjObj
paths:
    /FormBindingJSONRender/:id:
        post:
            consumes:
                - application/x-www-form-urlencoded
            description: 'FormBindingJSONRender '
            externalDocs: {}
            operationId: /demo.ObjObj/FormBindingJSONRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: formData
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
                - in: formData
                  name: address
                  required: true
                  type: string
            produces:
                - application/json
            responses: {}
            security: []
            summary: FormBindingJSONRender
    /FormMultipartBindingAsciiJSONRender/:id:
        post:
            consumes:
                - multipart/form-data
            description: 'FormMultipartBindingAsciiJSONRender '
            externalDocs: {}
            operationId: /demo.ObjObj/FormMultipartBindingAsciiJSONRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: formData
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
                - in: formData
                  name: address
                  required: true
                  type: string
            produces:
                - application/json
            responses: {}
            security: []
            summary: FormMultipartBindingAsciiJSONRender
    /FormPostBindingPureJSONRender/:id:
        post:
            consumes:
                - application/x-www-form-urlencoded
            description: 'FormPostBindingPureJSONRender '
            externalDocs: {}
            operationId: /demo.ObjObj/FormPostBindingPureJSONRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: formData
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
                - in: formData
                  name: address
                  required: true
                  type: string
            produces:
                - application/json
            responses: {}
            security: []
            summary: FormPostBindingPureJSONRender
    /HeaderBindingJsonpJSONRender/:id:
        get:
            consumes:
                - ""
            description: 'HeaderBindingJsonpJSONRender '
            externalDocs: {}
            operationId: /demo.ObjObj/HeaderBindingJsonpJSONRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: query
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
            produces:
                - application/javascript
            responses: {}
            security: []
            summary: HeaderBindingJsonpJSONRender
    /JSONBindingJSONRender/:id:
        post:
            consumes:
                - application/json
            description: 'JSONBindingJSONRender '
            externalDocs: {}
            operationId: /demo.ObjObj/JSONBindingJSONRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: formData
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
                - in: body
                  name: address
                  required: true
                  type: string
            produces:
                - application/json
            responses: {}
            security: []
            summary: JSONBindingJSONRender
    /MsgPackBindingMsgPackRender:
        delete:
            consumes:
                - application/x-msgpack
            description: 'MsgPackBindingMsgPackRender '
            externalDocs: {}
            operationId: /demo.ObjObj/MsgPackBindingMsgPackRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: formData
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
                - in: body
                  name: Address
                  required: true
                  type: string
            produces:
                - application/x-msgpack
            responses: {}
            security: []
            summary: MsgPackBindingMsgPackRender
    /ProtoBufBindingProtoBufRender:
        put:
            consumes:
                - application/x-protobuf
            description: 'ProtoBufBindingProtoBufRender '
            externalDocs: {}
            operationId: /demo.ObjObj/ProtoBufBindingProtoBufRender
            produces:
                - application/x-protobuf
            responses: {}
            security: []
            summary: ProtoBufBindingProtoBufRender
    /ProtoJSONBindingProtoJSONRender:
        put:
            consumes:
                - application/json
            description: 'ProtoJSONBindingProtoJSONRender '
            externalDocs: {}
            operationId: /demo.ObjObj/ProtoJSONBindingProtoJSONRender
            produces:
                - application/json
            responses: {}
            security: []
            summary: ProtoJSONBindingProtoJSONRender
    /QueryBindingSecureJSONRender/:id:
        get:
            consumes:
                - ""
            description: 'QueryBindingSecureJSONRender '
            externalDocs: {}
            operationId: /demo.ObjObj/QueryBindingSecureJSONRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: query
                  name: name
                  required: true
                  type: string
            produces:
                - application/json
            responses: {}
            security: []
            summary: QueryBindingSecureJSONRender
    /TOMLBindingTOMLRender/:id:
        put:
            consumes:
                - application/toml
            description: 'TOMLBindingTOMLRender '
            externalDocs: {}
            operationId: /demo.ObjObj/TOMLBindingTOMLRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: formData
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
                - in: body
                  name: address
                  required: true
                  type: string
            produces:
                - application/toml
            responses: {}
            security: []
            summary: TOMLBindingTOMLRender
    /UriBindingIndentedJSONRender/:id:
        get:
            consumes:
                - ""
            description: 'UriBindingIndentedJSONRender '
            externalDocs: {}
            operationId: /demo.ObjObj/UriBindingIndentedJSONRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
            produces:
                - application/json
            responses: {}
            security: []
            summary: UriBindingIndentedJSONRender
    /XMLBindingXMLRender/:id:
        patch:
            consumes:
                - application/xml
            description: 'XMLBindingXMLRender '
            externalDocs: {}
            operationId: /demo.ObjObj/XMLBindingXMLRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: formData
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
                - in: body
                  name: address
                  required: true
                  type: string
            produces:
                - application/xml
            responses: {}
            security: []
            summary: XMLBindingXMLRender
    /YAMLBindingYAMLRender/:id:
        delete:
            consumes:
                - application/x-yaml
            description: 'YAMLBindingYAMLRender '
            externalDocs: {}
            operationId: /demo.ObjObj/YAMLBindingYAMLRender
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: formData
                  name: name
                  required: true
                  type: string
                - in: header
                  name: Authorization
                  required: true
                  type: string
                - in: body
                  name: address
                  required: true
                  type: string
            produces:
                - application/x-yaml
            responses: {}
            security: []
            summary: YAMLBindingYAMLRender
    /all/:id/user/:user:
        get:
            consumes:
                - application/json
            description: 'AllRequest is http api '
            externalDocs: {}
            operationId: /demo.ObjObj/AllRequest
            parameters:
                - description: |-
                    I comment 1
                    comment 2
                    comment 3
                  in: path
                  name: i
                  required: true
                  type: integer
                - description: |-
                    comment 2
                    comment 3
                  in: query
                  name: i8
                  required: true
                  type: integer
                - in: header
                  name: i16
                  required: true
                  type: integer
                - in: body
                  name: I32
                  required: true
                  type: integer
                - in: body
                  name: I64
                  required: true
                  type: integer
                - in: body
                  name: U
                  required: true
                  type: integer
                - in: body
                  name: U8
                  required: true
                  type: integer
                - in: body
                  name: U16
                  required: true
                  type: integer
                - in: body
                  name: U32
                  required: true
                  type: integer
                - in: body
                  name: U64
                  required: true
                  type: integer
                - in: body
                  name: F32
                  required: true
                  type: number
                - in: body
                  name: F64
                  required: true
                  type: number
                - in: body
                  name: B
                  required: true
                  type: boolean
                - in: body
                  name: S
                  required: true
                  type: string
                - in: body
                  name: bs
                  required: true
                  type: string
                - in: body
                  items:
                    type: integer
                  name: A
                  required: true
                  type: array
                - in: body
                  name: UriBindingReq
                  required: true
                  type: object
                - {}
                - in: body
                  name: UriBindingReqPtrs
                  required: true
                  type: array
                - in: body
                  name: ProtoBufReqs
                  required: true
                  type: array
                - in: body
                  name: ProtoBufReqPtrs
                  required: true
                  type: array
            produces:
                - application/json
            responses: {}
            security: []
            summary: AllRequest
produces:
    - application/json
    - application/json
    - application/json
    - application/javascript
    - application/json
    - application/xml
    - application/json
    - application/json
    - application/json
    - application/x-protobuf
    - application/x-msgpack
    - application/x-yaml
    - application/toml
    - application/json
schemes:
    - http
    - https
swagger: "2.0"
