basePath: /api/ReaderReader
consumes:
    - ""
    - video/mp3
    - application/json
externalDocs: {}
id: ReaderReader
info:
    description: 'ReaderReader '
    title: ReaderReader
paths:
    /Get:
        get:
            consumes:
                - ""
            description: 'GetReaderReader '
            externalDocs: {}
            operationId: /demo.ReaderReader/GetReaderReader
            parameters:
                - in: body
                  required: true
            produces:
                - ""
            responses: {}
            security: []
            summary: GetReaderReader
    /get/json:
        get:
            consumes:
                - application/json
            description: 'GetJSONReader '
            externalDocs: {}
            operationId: /demo.ReaderReader/GetJSONReader
            produces:
                - video/mp4
            responses: {}
            security: []
            summary: GetJSONReader
    /head:
        head:
            consumes:
                - video/mp3
            description: 'HeadReaderReader '
            externalDocs: {}
            operationId: /demo.ReaderReader/HeadReaderReader
            parameters:
                - in: body
                  required: true
            produces:
                - video/mp4
            responses: {}
            security: []
            summary: HeadReaderReader
produces:
    - ""
    - video/mp4
    - video/mp4
schemes:
    - http
    - https
swagger: "2.0"
