basePath: /api/StringString
consumes:
    - ""
    - ""
externalDocs: {}
id: StringString
info:
    description: 'StringString '
    title: StringString
paths:
    /Get:
        get:
            consumes:
                - ""
            description: 'GetStringString '
            externalDocs: {}
            operationId: /demo.StringString/GetStringString
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - text/go
            responses: {}
            security: []
            summary: GetStringString
    /Patch:
        patch:
            consumes:
                - ""
            description: 'PatchStringString '
            externalDocs: {}
            operationId: /demo.StringString/PatchStringString
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - application/go
            responses: {}
            security: []
            summary: PatchStringString
produces:
    - text/go
    - application/go
schemes:
    - http
    - https
swagger: "2.0"
