basePath: /api/StringBytes
consumes:
    - ""
    - ""
externalDocs: {}
id: StringBytes
info:
    description: 'StringBytes '
    title: StringBytes
paths:
    /Get:
        get:
            consumes:
                - ""
            description: 'GetStringBytes '
            externalDocs: {}
            operationId: /demo.StringBytes/GetStringBytes
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - ""
            responses: {}
            security: []
            summary: GetStringBytes
    /Options:
        options:
            consumes:
                - ""
            description: 'OptionsStringBytes '
            externalDocs: {}
            operationId: /demo.StringBytes/OptionsStringBytes
            parameters:
                - in: body
                  name: body
                  schema:
                    type: string
            produces:
                - ""
            responses: {}
            security: []
            summary: OptionsStringBytes
produces:
    - ""
    - ""
schemes:
    - http
    - https
swagger: "2.0"
